### ISSUE TITLE
Would be possible to use aliases inside .yaml files (to cross-reference rows inside same file)?

### ISSUE THREAD

**Issue by pocaba** [simonw/yaml-to-sqlite#7]
I'm trying to use this in order to use _.yaml_ files as Meeting Notes, and then store meetings info into the sqlite db.
Main value it will provide is being able to query which **agreements** were taken and **when they were taken** (by pointing the '**_agreement_date_**' to the '**_&date_**'), despite of providing other informational session of each meeting.

`
[meeting_notes.yaml.txt](https://github.com/simonw/yaml-to-sqlite/files/8393529/meeting_notes.yaml.txt)
`

I'm guessing some meetin_notes.yaml file like:

```
- meeting_name: weekly
  &date: 20220330
  attendees:
  - Potato Mendez
  - Emily Laughter
  - Paul Bean
  absences:
  - Johny Walker
  - Rose White
  agenda:
  - Topic 1
  - Topic 2
  - Topic 3
  - Topic 4
  session_development:
  - Explanation about how 
  - the meeting has been evolved.
  Agreements:
  -
    agreement_date: *date
    tag: participation
    summary: This is the first agreement taken on this meeting.
    method: consens
  -
    agreement_date: *date
    tag: work
    summary: This is the second agreement taken on this meeting
    method: votation
```

Thanks all for your work! <3
